### ISSUE TITLE
Management Auth Token requires re-authentication (should be in README)

### ISSUE THREAD

**Issue by thebucknerlife** [contentful/contentful-space-sync#68] opened 2016-03-01 19:58 UTC
Hi there,

When you create a new space, you must re-create your Management Oauth token. For some reason, an old management token cannot be used against a new space, even when the token is for the Administrator of the space.

It would be really helpful if this detail was in the README, as it isn't mentioned here or in the Contentful Authentication docs.

Thanks! Happy to open a PR and add this detail myself if you like.

Greg

**Comment by trodrigues** [comment] 2016-03-02 09:18
Hi Greg,

well that shouldn't be the case, so I'd like to try and understand this better as there might be some confusion here.

A management token (the one you can get [here](https://www.contentful.com/developers/docs/references/authentication/#getting-an-oauth-token)) is attached to your user account.

Any space that your user has access to, can be managed with this access token.

The only reason as to why you'd need to use a separate management access token, is if your user doesn't have access to that space, and you need to login to a separate account.

This is why on the options we have `--management-token `, which is used for both source and destination spaces, and `--source-management-token` and `--destination-management-token` for when you're using the tool with two spaces that can't be access by the same user (and therefore, by the same access token).

The token that you do need to recreate for each space is the Delivery API token (which you can create under the API section in app.contentful.com). The delivery API tokens are attached to each space, and not to the user, and you can have multiple ones per space (for instance, one for an iOS app, another for a web app, etc).

Does that make sense and help clear anything up?

If you do need to recreate your management access token for each new space and if your user does have access to that space, than that is a bug with the Contentful authentication system and I can make sure that information gets passed along.

**Comment by maiers** [comment] 2016-03-18 11:31
Same here. I had to logout/login to create a new Management Token. It did not work with the old token which existed before the new space had been created. Btw I have the owner role for the organization and all it's spaces.

**Comment by trodrigues** [comment] 2016-04-05 15:52
As explained before, this is an issue we cannot reproduce and see no reason as to why this could happen. If someone can come up with some more helpful output or reproduction steps we'd be happy to look at it, but until then I will close this issue.

**Closed by trodrigues** 2016-04-05 15:52 UTC
