### ISSUE TITLE
Using as library fails with `managementToken`

### ISSUE THREAD

**Issue by tnunes** [contentful/contentful-space-sync#102] opened 2016-11-17 11:01 UTC
Using the tool as a CLI, we can use the `management-token` parameter when it is shared by both source and destination spaces, as stated in the docs.

When trying to use this parameter through the JS API (as `managementToken`), we're getting `TypeError: Expected parameter accessToken` thrown.

Currently, the tool only works as a library if specifying both `sourceManagementToken` and `destinationManagementToken` as `opts` properties to the `runSpaceSync` function, even if they have the same value.

**Comment by Khaledgarbaya** [comment] 2016-11-17 12:33
Thanks @tnunes ,
I will work on a fix asap
Best,
Khaled

**Comment by Khaledgarbaya** [comment] 2016-11-17 12:33
@tnunes  can you show me a snippet of code on how you pass the params to the library ?

**Comment by Khaledgarbaya** [comment] 2016-11-17 12:47
it is not clear in the documentation but your options object should like something like this: 
```
{
  opts{
    managementToken: '',
    sourceSpace: '',
    destinationSpace: ''
  },
  syncTokenFile : 'TOKEN_FILE'
}
```

**Comment by tnunes** [comment] 2016-11-17 13:56
Hi @Khaledgarbaya,

I'm passing parameters like you described.

Since it's currently not working if trying to do it like this:

```
  {
    syncTokenFile: '',
    opts: {
      sourceSpace: '',
      destinationSpace: '',
      sourceDeliveryToken: '',
      managementToken: ''
    }
  }
```

I'm working around it like this, even though `sourceManagementToken === destinationManagementToken`:

```
  {
    syncTokenFile: '',
    opts: {
      sourceSpace: '',
      destinationSpace: '',
      sourceDeliveryToken: '',
      sourceManagementToken: '',
      destinationManagementToken: ''
    }
  }
```

**Comment by Khaledgarbaya** [comment] 2016-11-17 14:58
Ah yeah I will fix that asap, the check to merge both token only done cli
side, sorry about that

**Comment by Khaledgarbaya** [comment] 2016-11-18 14:34
Hi @tnunes ,
Can you test with the branch referenced in this issue and confirm that the issue is fixed, if so I will merge it to master.

Best,
Khaled

**Comment by tnunes** [comment] 2016-11-22 11:46
This one seems to be fixed. Left comment in https://github.com/contentful/contentful-space-sync/issues/103#issuecomment-262218974 mentioning this.

**Comment by Khaledgarbaya** [comment] 2016-11-22 12:32
@tnunes I pushed a fix, can you test again?

**Closed** 2016-11-22 12:36 UTC
Labels: bug
