### ISSUE TITLE
TypeError: expecting an array or an iterable object but got [object Null]

### ISSUE THREAD

**Issue by duncanh** [contentful/contentful-space-sync#100] opened 2016-11-14 17:52 UTC
Environment: node 4.5.0, contentful-space-sync 4.1.1, client OSX 10.9.5

Hey guys - just trying to use the tool for the first time to sync between two spaces and getting this trace below (space ids removed). The destination space is completely empty and has no content model. I've had a look at the source of this library and bluebird and can't see anything obvious. Have also confirmed that the sync API is bringing data back, by adding some debug statements, but am still stumped - any help/suggestions you can offer would be much appreciated..

```
$ contentful-space-sync --config credentials.json
info Contentful Space Sync:
Let's sync some content across spaces! 
info No previous sync token found.
Synchronizing fresh content from [def] to [xyz] 
info Getting content from source space via the sync api 
info Checking if destination space already has any content and retrieving it 
ERR! Failed with
 TypeError: expecting an array or an iterable object but got [object Null]
ERR! Failed with
     at apiRejection (/Users/duncan/.nvm/v4.5.0/lib/node_modules/contentful-space-sync/node_modules/bluebird/js/release/promise.js:10:27)
ERR! Failed with
     at MappingPromiseArray.init (/Users/duncan/.nvm/v4.5.0/lib/node_modules/contentful-space-sync/node_modules/bluebird/js/release/promise_array.js:62:19)
ERR! Failed with
     at MappingPromiseArray._asyncInit (/Users/duncan/.nvm/v4.5.0/lib/node_modules/contentful-space-sync/node_modules/bluebird/js/release/map.js:30:10)
ERR! Failed with
     at Async._drainQueue (/Users/duncan/.nvm/v4.5.0/lib/node_modules/contentful-space-sync/node_modules/bluebird/js/release/async.js:143:12)
ERR! Failed with
     at Async._drainQueues (/Users/duncan/.nvm/v4.5.0/lib/node_modules/contentful-space-sync/node_modules/bluebird/js/release/async.js:148:10)
ERR! Failed with
     at Immediate.Async.drainQueues [as _onImmediate] (/Users/duncan/.nvm/v4.5.0/lib/node_modules/contentful-space-sync/node_modules/bluebird/js/release/async.js:17:14)
ERR! Failed with
     at processImmediate [as _immediateCallback] (timers.js:383:17)
ERR! Failed with
  [TypeError: expecting an array or an iterable object but got [object Null]]
```

**Comment by Khaledgarbaya** [comment] 2016-11-14 19:45
hi @duncanh ,
are you running the tool from source or from `npm nstall -g contentful-space-sync` ?
This is very weird never seen this before.

**Comment by duncanh** [comment] 2016-11-14 19:53
hey @Khaledgarbaya, I'm running it from `npm nstall -g contentful-space-sync`. In case it's relevant my node is managed with nvm, output of `nvm ls` is;
```
  v0.10.21
  v0.10.23
  v0.10.25
  v0.11.11
    v4.5.0
current: 	v4.5.0
default -> 0.10 (-> v0.10.25)
```
and I'm using v 2.15.9 of npm.

**Comment by Khaledgarbaya** [comment] 2016-11-14 20:09
@duncanh ,
Sorry one more question, can you show me the structure of the json file you are using ?

**Comment by duncanh** [comment] 2016-11-14 20:15
sure thing (sanitized)
```

{
  "sourceSpace": "source_space_id",
  "destinationSpace": "dest_space_id",
  "sourceDeliveryToken": "my_source_delivery_token",
  "managementToken": "my_management_token"
}
```

**Comment by Khaledgarbaya** [comment] 2016-11-14 20:17
ok, I will investigate this further meanwhile, can you clone the source and `npm install && npm run build` and run the tool locally `./bin/space-sync --config credentials.json`.

**Comment by duncanh** [comment] 2016-11-14 20:35
Hmm sorry - I get the same problem. I'm now wondering if I'm doing something stupid. I know the credentials and space ids are right though because I put deliberately wrong ones in and get the expected auth errors.

```
$ ./bin/space-sync --config credentials.json 
info Contentful Space Sync:
Let's sync some content across spaces! 
info No previous sync token found.
Synchronizing fresh content from [abc] to [xyz] 
info Getting content from source space via the sync api 
info Checking if destination space already has any content and retrieving it 
ERR! Failed with
 TypeError: expecting an array or an iterable object but got [object Null]
ERR! Failed with
     at apiRejection (/Users/duncan/Downloads/contentful-space-sync-master/node_modules/bluebird/js/release/promise.js:10:27)
ERR! Failed with
     at MappingPromiseArray.init (/Users/duncan/Downloads/contentful-space-sync-master/node_modules/bluebird/js/release/promise_array.js:62:19)
ERR! Failed with
     at MappingPromiseArray._asyncInit (/Users/duncan/Downloads/contentful-space-sync-master/node_modules/bluebird/js/release/map.js:30:10)
ERR! Failed with
     at Async._drainQueue (/Users/duncan/Downloads/contentful-space-sync-master/node_modules/bluebird/js/release/async.js:143:12)
ERR! Failed with
     at Async._drainQueues (/Users/duncan/Downloads/contentful-space-sync-master/node_modules/bluebird/js/release/async.js:148:10)
ERR! Failed with
     at Immediate.Async.drainQueues [as _onImmediate] (/Users/duncan/Downloads/contentful-space-sync-master/node_modules/bluebird/js/release/async.js:17:14)
ERR! Failed with
     at processImmediate [as _immediateCallback] (timers.js:383:17)
ERR! Failed with
  [TypeError: expecting an array or an iterable object but got [object Null]]
```

**Comment by duncanh** [comment] 2016-11-14 20:54
There is an [issue](https://github.com/petkaantonov/bluebird/issues/1045) on bluebird giving rise to the same error message that I'm getting. I tried to make the recommended change in line 4 of run-space-sync.js and re-run it but it didn't have any effect.

**Comment by Khaledgarbaya** [comment] 2016-11-14 21:00
I don't think the error is happening there it is happening around [here](https://github.com/contentful/contentful-batch-libs/blob/master/lib/get/get-outdated-destination-content.js#L21) and if I recall correctly that code did not change since a long time.
btw I am having the same error, I will try to fix this first thing tomorrow when I am back in the office.
Sorry for having this issue

**Comment by duncanh** [comment] 2016-11-14 21:04
Hey @Khaledgarbaya thanks very much for looking into it  ..

**Comment by Khaledgarbaya** [comment] 2016-11-14 21:04
@duncanh you can try better tools [contentful-export](https://github.com/contentful/contentful-export) for exporting your content to json file and [contentful-import](https://github.com/contentful/contentful-import) to import the exported json. For now

**Comment by szimek** [comment] 2016-11-15 14:51
I'm just trying to copy data between spaces for the first time using contentful-space-sync 4.1.1 and it fails with exactly the same error. I've got node 7.1.0.

@Khaledgarbaya Thanks for the tip. I'll try these export/import tools then instead ;)

**Comment by Khaledgarbaya** [comment] 2016-11-15 15:32
@szimek, I am still investigating what is causing the problem, should be fixed soon

**Comment by Khaledgarbaya** [comment] 2016-11-15 15:52
@szimek and @duncanh The issue is fixed, it was not related to bluebird it was something introduced when creating the contentful-export and contentful-import tool. Sorry about that.
I will release a fix in few minutes.
Again really sorry guys about the issue

**Closed** 2016-11-15 16:21 UTC

**Comment by szimek** [comment] 2016-11-15 16:27
@Khaledgarbaya Thanks!

**Comment by Khaledgarbaya** [comment] 2016-11-15 16:27
v4.1.2 is the fixed version

**Comment by duncanh** [comment] 2016-11-15 16:35
@Khaledgarbaya Thanks for addressing that so quickly - will check it out. In the meantime, I did follow your suggestion with the other libraries and that worked for me. :)
